import { useState } from 'react';
import { animeFavourites } from '../data/profile';
export function AnimeIcon({size=18}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M3 10c3-5 6-7 9-7s6 2 9 7M3 10l3 8 6 3 6-3 3-8M5 8l2 6 3-1m9-5-2 6-3-1M9 17l3 1 3-1M9 4l3 5 3-5"/></svg>;}
const stories=[
  {id:'voyage',chapter:'01 / THE GRAND VOYAGE',word:'ADVENTURE',caption:'One more island. One more impossible dream.',tone:'amber',image:'one-piece',source:'https://www.toei-animation.com/catalog/one-piece/',credit:'Eiichiro Oda / Shueisha / Toei Animation'},
  {id:'moon',chapter:'02 / THE NIGHT RAID',word:'RESOLVE',caption:'Some stories stay long after the credits.',tone:'crimson',image:'akame-ga-kill',source:'http://akame.tv/',credit:'Akame ga Kill official anime website'},
  {id:'compass',chapter:'03 / THE NEXT HORIZON',word:'CURIOSITY',caption:'There is always a bigger world to discover.',tone:'jade',image:'hunter-x-hunter',source:'https://www.ntv.co.jp/hunterhunter/',credit:'Yoshihiro Togashi / Shueisha / HUNTER x HUNTER production committee'},
];
export function AnimeArchive(){const [selected,setSelected]=useState(0),story=stories[selected];return <div className={`anime-library anime-${story.tone}`}><div className="anime-library-intro"><span className="eyebrow">OFF DUTY / FULL-TIME WEEB</span><h3>A hundred worlds.<br/>Still room for one more.</h3><p>I've probably watched over 100 anime by now. These three have a permanent place in my all-time favourites.</p></div><div className="anime-shelf" role="tablist" aria-label="Favourite anime">{animeFavourites.map((name,i)=><button key={name} role="tab" tabIndex={selected===i?0:-1} id={`anime-tab-${i}`} aria-controls="anime-panel" aria-selected={selected===i} onClick={()=>setSelected(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const n=(i+(e.key==='ArrowRight'?1:2))%3;setSelected(n);document.getElementById(`anime-tab-${n}`)?.focus();}}}><span>0{i+1}</span><b>{name}</b><AnimeIcon/></button>)}</div><div id="anime-panel" role="tabpanel" aria-labelledby={`anime-tab-${selected}`} className="anime-feature" key={selected}><img className="archive-official-art" src={`/assets/anime/${story.image}.webp`} alt={`${animeFavourites[selected]} official promotional artwork`} width={600} height={650} decoding="async"/><div className="anime-feature-copy"><span className="eyebrow">{story.chapter}</span><h4>{animeFavourites[selected]}</h4><p>{story.caption}</p><span className="anime-theme">{story.word}</span><a className="anime-source" href={story.source} target="_blank" rel="noreferrer">Official anime site ?</a></div></div><p className="archive-footnote">Artwork: {story.credit}. Shown as part of my personal favourites.</p></div>;}
