import { Map, FileText, Volume2, VolumeX, Minus, ArrowLeft, ArrowRight, BriefcaseBusiness, Feather } from 'lucide-react';
import { worlds, type WorldId } from '../data/worlds';
import { profile } from '../data/profile';
export function Hud({index,progress,muted,lightweight,onMap,onBriefing,onMute,onMode,navigate}:{index:number;progress:number;muted:boolean;lightweight:boolean;onMap:()=>void;onBriefing:()=>void;onMute:()=>void;onMode:()=>void;navigate:(id:WorldId)=>void}) {
  return <>
    <header className="hud"><button className="brand" onClick={()=>navigate('spawn')} aria-label="Go to Spawn">DARSHAN<span>.</span>WORLD</button><nav aria-label="Global controls"><button className="hud-button briefing-button" onClick={onBriefing} aria-label="Quick briefing"><BriefcaseBusiness size={15}/><span>Quick briefing</span></button><button className="hud-button" onClick={onMap} aria-label="World map"><Map size={16}/><span>World map</span></button><a className="hud-button resume-button" href={profile.resumeUrl} aria-label="View Resume"><FileText size={15}/><span>View Resume</span></a><button className={`icon-button sound-control ${muted?'':'sound-playing'}`} onClick={onMute} aria-label={muted?'Enable sound':'Mute sound'} aria-pressed={!muted}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}<span className="sound-bars" aria-hidden="true"><i/><i/><i/></span></button></nav></header>
    <aside className="world-edge" aria-hidden="true"><span>{worlds[index].keyword}</span><i/><span>CHAPTER {worlds[index].icon}</span></aside>
    <footer className="journey-hud"><div className="chapter-info"><span>{worlds[index].icon}<small>/ 07</small></span><div><b>{worlds[index].name}</b><small>{worlds[index].subtitle}</small></div></div><nav className="chapter-dots" aria-label="World destinations">{worlds.map((w,i)=><button key={w.id} className={i===index?'active':''} aria-label={`Go to ${w.name}`} aria-current={i===index?'location':undefined} onClick={()=>navigate(w.id)}><span/><small>{w.icon}</small></button>)}</nav><div className="journey-controls"><button className="icon-button" onClick={()=>navigate(worlds[Math.max(0,index-1)].id)} aria-label="Previous world" disabled={index===0}><ArrowLeft size={17}/></button><button className="icon-button" onClick={()=>navigate(worlds[Math.min(6,index+1)].id)} aria-label="Next world" disabled={index===6}><ArrowRight size={17}/></button><Minus size={16} className="divider-icon"/><button className="icon-button mode-button" onClick={onMode} aria-label={lightweight?'Enable cinematic mode':'Enable lightweight mode'} aria-pressed={lightweight} title={lightweight?'Enable cinematic mode':'Enable lightweight mode'}><Feather size={16}/></button></div><div className="journey-track" aria-hidden="true"><span style={{transform:`scaleX(${progress})`}}/></div></footer>
  </>;
}
