import { memo, useState } from 'react';
import { AnimeIcon } from './AnimeArchive';
import { roadBikeOpacity, spawnPortraitOpacity } from '../lib/routeLayout';
import { BikeImage } from './BikeImage';
import { ArrowRight, ArrowUpRight, Mountain, Moon, Waves, Gamepad2, Send, GitBranch } from 'lucide-react';
import { profile, skillGroups, communityStats } from '../data/profile';
import { projects } from '../data/projects';
import type { WorldId } from '../data/worlds';
export const WorldContent=memo(function WorldContent({progress,index,project,setProject,roadBeat,setRoadBeat,portrait,hasBike,navigate,open}:{progress:number;index:number;project:number;setProject:(n:number)=>void;roadBeat:number;setRoadBeat:(n:number)=>void;portrait:string;hasBike:boolean;navigate:(id:WorldId)=>void;open:(value:string)=>void}) {
  const [skills,setSkills]=useState(0);const p=projects[project];
  return <main id="world-content" tabIndex={-1} className={`world-content world-${index}`}>
    {index===0&&<>
      <div className="portrait-stage" aria-hidden="true" style={{visibility:spawnPortraitOpacity(progress)>0?'visible':'hidden'}}>{portrait&&<img src={portrait} alt="" style={{opacity:spawnPortraitOpacity(progress)}}/>}<span className="portrait-tag" style={{opacity:spawnPortraitOpacity(progress)*.6}}>THE HUMAN BEHIND THE IDEAS</span></div>
      <div className="narrative spawn-copy"><span className="eyebrow">01 / SPAWN POINT · BENGALURU, INDIA</span><h1 className="name-title">DARSHAN<br/><span>KRISHNA N</span></h1><p className="spawn-roles">DEVELOPER <i/> DEVREL <i/> BUILDER <i/> EXPLORER</p><p className="lead">Turning technology into things people can use, understand and rally around.</p><div className="identity"><span>CLASS<b>BUILDER</b></span><span>SPECIALTY<b>DEVREL</b></span><span>SIDE QUEST<b>SOLO ENTREPRENEUR</b></span><span>COMPANION<b>GUNDU</b></span></div><div className="world-actions"><button className="button" onClick={()=>navigate('devlab')}>Start exploring<ArrowRight size={17}/></button><button className="text-button" onClick={()=>open('briefing')}>Meet the human<ArrowUpRight size={15}/></button></div></div>
    </>}
    {index===1&&<div className="narrative lab-copy"><span className="eyebrow">02 / DEVLAB · THE IDEA ENGINE</span><h1>I BUILD THINGS<br/><em>I WISH EXISTED.</em></h1><p className="lead">Products and data workflows, built with intent.</p><div className="workstation-tabs" role="group" aria-label="Skill workstations">{skillGroups.map((g,i)=><button aria-pressed={skills===i} onClick={()=>setSkills(i)} key={g.name}>{g.name}</button>)}</div><div className="workstation" aria-live="polite"><p className="skills-type">{skillGroups[skills].skills.map(s=><span key={s}>{s}</span>)}</p></div><div className="current-role"><span>JLL TECHNOLOGIES · AUG 2024-PRESENT</span><b>Data Quality &amp; Governance Analyst I</b></div><div className="world-actions"><button className="button" onClick={()=>open('work')}>Inside my work<ArrowUpRight size={16}/></button><button className="text-button" onClick={()=>open('agents')}><GitBranch size={16}/> My agentic toolchain</button></div></div>}
    {index===2&&<div className="narrative project-copy"><span className="eyebrow">03 / PROJECTS · IDEAS WITH PURPOSE</span><div className="project-select" role="group" aria-label="Select a product">{projects.map((item,i)=><button onClick={()=>setProject(i)} key={item.id} aria-pressed={project===i}><span>0{i+1}</span>{item.name}</button>)}</div><div className="selected-project" key={project}><span className="eyebrow">{p.label}</span><h1>{p.headline}</h1><p className="lead">{p.summary}</p><div className="project-tech">{p.tech.slice(0,4).join(' / ')}</div><button className="button" onClick={()=>open(`project-${project}`)}>Explore {p.name}<ArrowRight size={17}/></button></div></div>}
    {index===3&&<div className="narrative community-copy"><span className="eyebrow">04 / DEVREL CITY · BETTER, TOGETHER</span><h1>CODE CREATES PRODUCTS.<br/><em>COMMUNITY CREATES MOVEMENTS.</em></h1><p className="lead">Founder, KrowdKraft. Creating spaces where developers learn, build and belong.</p><div className="community-ledger">{communityStats.map((s,i)=><div key={s.label}><b>{s.value.split('').map((char,n)=>n===0||char==='5'?<span className="stat-lead" key={n}>{char}</span>:char)}</b><span>{['MEMBERS','EVENTS','REACHED','TALKS','TRAINED'][i]}</span></div>)}</div><button className="button" onClick={()=>open('community')}>The people. The work. The why.<ArrowUpRight size={16}/></button></div>}
    {index===4&&<>
      {roadBeat!==2&&hasBike&&<div className={`bike-stage ${roadBeat===1?'midnight':''}`} style={{opacity:roadBikeOpacity(progress),visibility:roadBikeOpacity(progress)===0?'hidden':'visible'}}><BikeImage/><span>YEZDI ADVENTURE 350 / MY RIDE</span></div>}
      <div className="narrative road-copy"><span className="eyebrow">05 / THE ROAD · TAKE THE LONG WAY</span><div className="road-tabs" role="group" aria-label="Travel story"><button aria-pressed={roadBeat===0} onClick={()=>setRoadBeat(0)}><Mountain size={15}/> The ride</button><button aria-pressed={roadBeat===1} onClick={()=>setRoadBeat(1)}><Moon size={15}/> Midnight ghats</button><button aria-pressed={roadBeat===2} onClick={()=>setRoadBeat(2)}><Waves size={15}/> The reset</button></div><div key={roadBeat} className="road-story">{roadBeat===0?<><h1>SOME IDEAS<br/><em>NEED OPEN ROADS.</em></h1><p className="lead">Long rides around Bengaluru. Beaches, hills, waterfalls and rivers. Always a reason to keep going.</p><div className="road-signs"><span>HILLS ↗</span><span>WATERFALLS ↗</span><span>KEEP RIDING →</span></div></>:roadBeat===1?<><span className="route-label">BENGALURU → UDUPI</span><h1>MIDNIGHT. THE GHATS.<br/><em>JUST ME AND THE ROAD.</em></h1><p className="lead">My favourite ride so far: solo through the spooky ghats. Some stories only happen after dark.</p></>:<><h1>MY RESET<br/><em>BUTTON.</em></h1><p className="lake-name">VATADAHOSAHALLI LAKE</p><p className="lead">My go-to nature reset near Bengaluru.<br/>No dashboard. No deadlines. Just water.</p></>}</div></div>
    </>}
    {index===5&&<div className="narrative arcade-copy"><span className="eyebrow">06 / ARCADE + ANIME ARCHIVE</span><h1>BUILD MODE: OFF.<br/><em>GAME ON.</em></h1><div className="player-sheet"><div><span>PLAYER</span><b>DARSHAN</b></div><div><span>ALIAS</span><b>BotLifeMatters</b></div><div><span>CURRENT</span><b>Mobile Legends: Bang Bang / PUBG</b></div><div><span>ALL-TIME FAVOURITE</span><b>CS:GO</b></div><div><span>ANIME</span><b>100+ (probably). Proud weeb.</b></div></div><div className="world-actions"><button className="button" onClick={()=>open('game')}><Gamepad2 size={17}/> Play a side quest</button><button className="text-button" onClick={()=>open('anime')}><AnimeIcon size={17}/> Anime archive</button></div></div>}
    {index===6&&<div className="narrative campfire-copy"><span className="eyebrow">07 / CAMPFIRE · STAY A WHILE</span><h1>GOOD THINGS<br/>START WITH<br/><em>A HELLO.</em></h1><p className="lead">Developer relations. Products. Communities.<br/>An idea worth building together. Pull up a seat.</p><div className="world-actions"><a className="button" href={`mailto:${profile.email}`}><Send size={16}/> Let's talk<ArrowUpRight size={16}/></a><button className="text-button" onClick={()=>open('briefing')}>Quick briefing</button></div><div className="socials">{profile.socials.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer">{s.name}<ArrowUpRight size={13}/></a>)}</div></div>}
  </main>;
});
