import { useEffect, useMemo, useRef } from 'react';
import { useFrame } from '@react-three/fiber';
import { AdditiveBlending, CanvasTexture, Color, DoubleSide, Float32BufferAttribute, PlaneGeometry, RepeatWrapping, ShaderMaterial, SRGBColorSpace } from 'three';
import { useMotionTime } from './Motion';
import { Instances, type Instance } from './Instances';
import { LightPool } from './Materials';
import { CampChair, campfireLayout } from './People';
export { RoadEnvironment } from './RoadScenery';
export { createRoadGeometry, roadCenter } from './roadGeometry';

import { Embers } from './Embers';
const vertex='varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}';
const noise='float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}';
function rand(i:number){return ((Math.sin(i*127.1+311.7)*43758.5453)%1+1)%1;}
function useEarthTexture(){const map=useMemo(()=>{const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d')!,image=ctx.createImageData(256,256);for(let y=0;y<256;y++)for(let x=0;x<256;x++){const n=rand(x+y*257)*.3+.35+.17*Math.sin(x*.13)*Math.cos(y*.18),i=(x+y*256)*4;image.data[i]=n*166;image.data[i+1]=n*177;image.data[i+2]=n*140;image.data[i+3]=255;}ctx.putImageData(image,0,0);const t=new CanvasTexture(c);t.colorSpace=SRGBColorSpace;t.wrapS=t.wrapT=RepeatWrapping;t.repeat.set(18,20);return t;},[]);useEffect(()=>()=>map.dispose(),[map]);return map;}
export function Terrain({lake=false,night=false,road=false}:{lake?:boolean;night?:boolean;road?:boolean}){const map=useEarthTexture();const geometry=useMemo(()=>{const g=new PlaneGeometry(90,road?62:42,80,60);g.rotateX(-Math.PI/2);const p=g.attributes.position,colors:number[]=[];for(let i=0;i<p.count;i++){const x=p.getX(i),z=p.getZ(i);const center=1.5+Math.sin((z-8)*.075)*2;const edge=Math.max(0,(Math.abs(x-center)-(lake?12:5))/10);const detail=Math.sin(x*.28+z*.14)*Math.cos(z*.21)*1.7+Math.sin(x*.83-z*.44)*.37+Math.cos(x*1.84+z*.73)*.13;const h=-1.76+edge*(5+detail*2+Math.cos(z*.095)*2)+(Math.abs(x)<5?Math.sin(x*1.8+z)*.026:detail*.15);p.setY(i,h);const c=new Color(night?'#5c6a68':'#779475').multiplyScalar(.8+Math.max(0,h+1.7)*.025);colors.push(c.r,c.g,c.b);}g.setAttribute('color',new Float32BufferAttribute(colors,3));g.computeVertexNormals();return g;},[lake,night,road]);useEffect(()=>()=>geometry.dispose(),[geometry]);return <mesh geometry={geometry} position={[0,0,road?-18:-8]}><meshStandardMaterial map={map} vertexColors roughness={1}/></mesh>;}
export function Forest({night=false,lake=false,road=false}:{night?:boolean;lake?:boolean;road?:boolean}){const data=useMemo(()=>{const trunks:Instance[]=[],leaves:Instance[]=[],branches:Instance[]=[];for(let i=0;i<88;i++){const side=i%2?1:-1,x=side*((lake?12:5.8)+rand(i*3)*10),z=3-(i%44)*(road?1.05:.65),h=3+rand(i+7)*4.8;trunks.push({position:[x,-1.7+h/2,z],scale:[.11,h,.11],color:night?'#292c27':'#3c3b2d'});for(let j=0;j<4;j++){const angle=j*2.4+i;const spread=.5+j*.12;leaves.push({position:[x+Math.sin(angle)*spread,-1.7+h*.73+j*.3,z+Math.cos(angle)*spread],scale:[1.1+rand(i+j)*.4,.75+rand(i*j)*.5,1.1],rotation:[i*.1,j*.6,i*.12],color:night?['#152d2d','#213733','#1b3029'][i%3]:['#426540','#507948','#537c4a','#385e3d'][(i+j)%4]});}branches.push({position:[x+.25,-1.7+h*.62,z],scale:[.055,h*.42,.055],rotation:[0,0,-.65],color:'#32372d'});}return {trunks,leaves,branches};},[night,lake,road]);return <><Instances shape="trunk" items={data.trunks}/><Instances shape="trunk" items={data.branches}/><Instances shape="foliage" items={data.leaves}/></>;}
function Undergrowth({lake=false,road=false}:{lake?:boolean;road?:boolean}){const grass=useMemo<Instance[]>(()=>Array.from({length:460},(_,i)=>{const x=(rand(i)-.5)*26,z=4-rand(i+200)*(road?48:30);return {position:[Math.abs(x)<4?(x<0?-4:4)+x*.2:x,-1.72,z],scale:[.8+rand(i)*.4,.32+rand(i*7)*.5,.8],rotation:[.1,rand(i+2)*6,(rand(i+1)-.5)*.4],color:['#3d5140','#3c4a33','#53614a'][i%3]};}),[road]);const rocks=useMemo<Instance[]>(()=>Array.from({length:75},(_,i)=>({position:[(i%2?1:-1)*((lake?11:4.5)+rand(i)*6),-1.52,4-rand(i+5)*(road?48:30)],scale:[.2+rand(i)*.55,.15+rand(i+8)*.4,.2+rand(i+10)*.5],rotation:[i,i*.7,i*.3],color:['#45524b','#56605a','#3d4945'][i%3]})),[lake,road]);return <><Instances items={grass} shape="grass"/><Instances items={rocks} shape="rock"/></>;}
function Fire(){const t=useMotionTime(),materials=useRef<(ShaderMaterial|null)[]>([]);useFrame(({clock})=>materials.current.forEach(m=>{if(m)m.uniforms.time.value=t(clock);}));return <>{[0,1,2].map(i=><mesh key={i} position={[0,.62,0]} rotation={[0,i*Math.PI/3,0]}><planeGeometry args={[1.2,1.9]}/><shaderMaterial ref={m=>{materials.current[i]=m;}} uniforms={{time:{value:0},seed:{value:i*7}}} transparent depthWrite={false} side={DoubleSide} blending={AdditiveBlending} vertexShader={vertex} fragmentShader={`varying vec2 vUv;uniform float time;uniform float seed;${noise}void main(){vec2 p=vUv;float n=noise(vec2(p.x*7.+seed,p.y*8.-time*2.7));float w=(1.-p.y)*.43;float center=.5+sin(p.y*8.-time*3.+seed)*p.y*.1;float a=1.-smoothstep(w*.2,w,abs(p.x-center)+n*.06);a*=smoothstep(0.,.09,p.y)*(1.-smoothstep(.65,1.,p.y));vec3 c=mix(vec3(.9,.13,.015),vec3(1.,.64,.18),pow(1.-p.y,2.));gl_FragColor=vec4(c,a*(.5+n*.25));}`}/></mesh>)}</>;}
export function CampfireEnvironment(){const stones=useMemo<Instance[]>(()=>Array.from({length:12},(_,i)=>({position:[Math.cos(i*Math.PI/6)*.9,-.23,Math.sin(i*Math.PI/6)*.9],scale:[.27,.16,.23],rotation:[i*.7,i*.9,i*.2],color:['#5d655b','#747166','#4b5752'][i%3]})),[]);return <group><Terrain night/><Forest night/><Undergrowth/><group position={[2.2,-1.15,0]}><Instances shape="rock" items={stones}/><Instances shape="trunk" items={[0,1,2].map(i=>({position:[0,0,0],scale:[.13,1.6,.13],rotation:[Math.PI/2,0,i*Math.PI/3],color:'#503622'}))}/><Fire/><LightPool position={[0,-.48,0]} color="#b57937" size={7} opacity={.3}/></group>{campfireLayout.chairs.map((chair,i)=><CampChair key={i} {...chair} occupied={i===1}/>)}
 <Embers/>
 </group>;}
